
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/var/home/wingdom/Android/cmake/3.31.5/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.17.7-ba20.fc43.x86_64 - x86_64
...
